const newGarden = [
  [
    { id: "aa", isUsed: false },
    { id: "ab", isUsed: false },
    { id: "ac", isUsed: false },
    { id: "ad", isUsed: false },
    { id: "ae", isUsed: false },
    { id: "af", isUsed: false },
    { id: "ag", isUsed: false },
    { id: "ah", isUsed: false },
    { id: "ai", isUsed: false },
    { id: "aj", isUsed: false },
    { id: "ak", isUsed: false },
    { id: "al", isUsed: false },
    { id: "am", isUsed: false },
    { id: "an", isUsed: false },
    { id: "ao", isUsed: false },
    { id: "ap", isUsed: false },
    { id: "aq", isUsed: false },
    { id: "ar", isUsed: false },
    { id: "as", isUsed: false },
  ],
  [
    { id: "ba", isUsed: false },
    { id: "bb", isUsed: false },
    { id: "bc", isUsed: false },
    { id: "bd", isUsed: false },
    { id: "be", isUsed: false },
    { id: "bf", isUsed: false },
    { id: "bg", isUsed: false },
    { id: "bh", isUsed: false },
    { id: "bi", isUsed: false },
    { id: "bj", isUsed: false },
    { id: "bk", isUsed: false },
    { id: "bl", isUsed: false },
    { id: "bm", isUsed: false },
    { id: "bn", isUsed: false },
    { id: "bo", isUsed: false },
    { id: "bp", isUsed: false },
    { id: "bq", isUsed: false },
    { id: "br", isUsed: false },
    { id: "bs", isUsed: false },
  ],
  [
    { id: "ca", isUsed: false },
    { id: "cb", isUsed: false },
    { id: "cc", isUsed: false },
    { id: "cd", isUsed: false },
    { id: "ce", isUsed: false },
    { id: "cf", isUsed: false },
    { id: "cg", isUsed: false },
    { id: "ch", isUsed: false },
    { id: "ci", isUsed: false },
    { id: "cj", isUsed: false },
    { id: "ck", isUsed: false },
    { id: "cl", isUsed: false },
    { id: "cm", isUsed: false },
    { id: "cn", isUsed: false },
    { id: "co", isUsed: false },
    { id: "cp", isUsed: false },
    { id: "cq", isUsed: false },
    { id: "cr", isUsed: false },
    { id: "cs", isUsed: false },
  ],
  [
    { id: "da", isUsed: false },
    { id: "db", isUsed: false },
    { id: "dc", isUsed: false },
    { id: "dd", isUsed: false },
    { id: "de", isUsed: false },
    { id: "df", isUsed: false },
    { id: "dg", isUsed: false },
    { id: "dh", isUsed: false },
    { id: "di", isUsed: false },
    { id: "dj", isUsed: false },
    { id: "dk", isUsed: false },
    { id: "dl", isUsed: false },
    { id: "dm", isUsed: false },
    { id: "dn", isUsed: false },
    { id: "do", isUsed: false },
    { id: "dp", isUsed: false },
    { id: "dq", isUsed: false },
    { id: "dr", isUsed: false },
    { id: "ds", isUsed: false },
  ],
  [
    { id: "ea", isUsed: false },
    { id: "eb", isUsed: false },
    { id: "ec", isUsed: false },
    { id: "ed", isUsed: false },
    { id: "ee", isUsed: false },
    { id: "ef", isUsed: false },
    { id: "eg", isUsed: false },
    { id: "eh", isUsed: false },
    { id: "ei", isUsed: false },
    { id: "ej", isUsed: false },
    { id: "ek", isUsed: false },
    { id: "el", isUsed: false },
    { id: "em", isUsed: false },
    { id: "en", isUsed: false },
    { id: "eo", isUsed: false },
    { id: "ep", isUsed: false },
    { id: "eq", isUsed: false },
    { id: "er", isUsed: false },
    { id: "es", isUsed: false },
  ],
  [
    { id: "fa", isUsed: false },
    { id: "fb", isUsed: false },
    { id: "fc", isUsed: false },
    { id: "fd", isUsed: false },
    { id: "fe", isUsed: false },
    { id: "ff", isUsed: false },
    { id: "fg", isUsed: false },
    { id: "fh", isUsed: false },
    { id: "fi", isUsed: false },
    { id: "fj", isUsed: false },
    { id: "fk", isUsed: false },
    { id: "fl", isUsed: false },
    { id: "fm", isUsed: false },
    { id: "fn", isUsed: false },
    { id: "fo", isUsed: false },
    { id: "fp", isUsed: false },
    { id: "fq", isUsed: false },
    { id: "fr", isUsed: false },
    { id: "fs", isUsed: false },
  ],
  [
    { id: "ga", isUsed: false },
    { id: "gb", isUsed: false },
    { id: "gc", isUsed: false },
    { id: "gd", isUsed: false },
    { id: "ge", isUsed: false },
    { id: "gf", isUsed: false },
    { id: "gg", isUsed: false },
    { id: "gh", isUsed: false },
    { id: "gi", isUsed: false },
    { id: "gj", isUsed: false },
    { id: "gk", isUsed: false },
    { id: "gl", isUsed: false },
    { id: "gm", isUsed: false },
    { id: "gn", isUsed: false },
    { id: "go", isUsed: false },
    { id: "gp", isUsed: false },
    { id: "gq", isUsed: false },
    { id: "gr", isUsed: false },
    { id: "gs", isUsed: false },
  ],
  [
    { id: "ha", isUsed: false },
    { id: "hb", isUsed: false },
    { id: "hc", isUsed: false },
    { id: "hd", isUsed: false },
    { id: "he", isUsed: false },
    { id: "hf", isUsed: false },
    { id: "hg", isUsed: false },
    { id: "hh", isUsed: false },
    { id: "hi", isUsed: false },
    { id: "hj", isUsed: false },
    { id: "hk", isUsed: false },
    { id: "hl", isUsed: false },
    { id: "hm", isUsed: false },
    { id: "hn", isUsed: false },
    { id: "ho", isUsed: false },
    { id: "hp", isUsed: false },
    { id: "hq", isUsed: false },
    { id: "hr", isUsed: false },
    { id: "hs", isUsed: false },
  ],
  [
    { id: "ia", isUsed: false },
    { id: "ib", isUsed: false },
    { id: "ic", isUsed: false },
    { id: "id", isUsed: false },
    { id: "ie", isUsed: false },
    { id: "if", isUsed: false },
    { id: "ig", isUsed: false },
    { id: "ih", isUsed: false },
    { id: "ii", isUsed: false },
    { id: "ij", isUsed: false },
    { id: "ik", isUsed: false },
    { id: "il", isUsed: false },
    { id: "im", isUsed: false },
    { id: "in", isUsed: false },
    { id: "io", isUsed: false },
    { id: "ip", isUsed: false },
    { id: "iq", isUsed: false },
    { id: "ir", isUsed: false },
    { id: "is", isUsed: false },
  ],
  [
    { id: "ja", isUsed: false },
    { id: "jb", isUsed: false },
    { id: "jc", isUsed: false },
    { id: "jd", isUsed: false },
    { id: "je", isUsed: false },
    { id: "jf", isUsed: false },
    { id: "jg", isUsed: false },
    { id: "jh", isUsed: false },
    { id: "ji", isUsed: false },
    { id: "jj", isUsed: false },
    { id: "jk", isUsed: false },
    { id: "jl", isUsed: false },
    { id: "jm", isUsed: false },
    { id: "jn", isUsed: false },
    { id: "jo", isUsed: false },
    { id: "jp", isUsed: false },
    { id: "jq", isUsed: false },
    { id: "jr", isUsed: false },
    { id: "js", isUsed: false },
  ],
  [
    { id: "ka", isUsed: false },
    { id: "kb", isUsed: false },
    { id: "kc", isUsed: false },
    { id: "kd", isUsed: false },
    { id: "ke", isUsed: false },
    { id: "kf", isUsed: false },
    { id: "kg", isUsed: false },
    { id: "kh", isUsed: false },
    { id: "ki", isUsed: false },
    { id: "kj", isUsed: false },
    { id: "kk", isUsed: false },
    { id: "kl", isUsed: false },
    { id: "km", isUsed: false },
    { id: "kn", isUsed: false },
    { id: "ko", isUsed: false },
    { id: "kp", isUsed: false },
    { id: "kq", isUsed: false },
    { id: "kr", isUsed: false },
    { id: "ks", isUsed: false },
  ],
  [
    { id: "la", isUsed: false },
    { id: "lb", isUsed: false },
    { id: "lc", isUsed: false },
    { id: "ld", isUsed: false },
    { id: "le", isUsed: false },
    { id: "lf", isUsed: false },
    { id: "lg", isUsed: false },
    { id: "lh", isUsed: false },
    { id: "li", isUsed: false },
    { id: "lj", isUsed: false },
    { id: "lk", isUsed: false },
    { id: "ll", isUsed: false },
    { id: "lm", isUsed: false },
    { id: "ln", isUsed: false },
    { id: "lo", isUsed: false },
    { id: "lp", isUsed: false },
    { id: "lq", isUsed: false },
    { id: "lr", isUsed: false },
    { id: "ls", isUsed: false },
  ],
  [
    { id: "ma", isUsed: false },
    { id: "mb", isUsed: false },
    { id: "mc", isUsed: false },
    { id: "md", isUsed: false },
    { id: "me", isUsed: false },
    { id: "mf", isUsed: false },
    { id: "mg", isUsed: false },
    { id: "mh", isUsed: false },
    { id: "mi", isUsed: false },
    { id: "mj", isUsed: false },
    { id: "mk", isUsed: false },
    { id: "ml", isUsed: false },
    { id: "mm", isUsed: false },
    { id: "mn", isUsed: false },
    { id: "mo", isUsed: false },
    { id: "mp", isUsed: false },
    { id: "mq", isUsed: false },
    { id: "mr", isUsed: false },
    { id: "ms", isUsed: false },
  ],
];

module.exports = newGarden;
